import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen bg-gradient-to-b from-[#020305] to-[#6475C8] relative overflow-hidden`}
      >
        <div
          className="absolute inset-0 bg-[url('/bg.png')] bg-cover bg-center opacity-15 z-[-1]"
          aria-hidden="true"
        />
        {children}
      </body>
    </html>
  );
}
